name: Build ROS Deb
run-name: ${{ github.actor }} is testing out building Debs from ROS package
on:
  workflow_dispatch:
  push:
jobs:
  jammy-humble-amd64:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
      #- uses: jspricke/ros-deb-builder-action@main
      # Use forked version of action that allows network
      # access by patching sbuild after its installed but
      # before it is built.
      # See https://github.com/jspricke/ros-deb-builder-action/issues/38
      - uses: aosmw/ros-deb-builder-action@feature/mw/enable_network
        with:
          DEB_DISTRO: jammy
          DEB_ARCH: amd64
          ROS_DISTRO: humble
          #SBUILD_CONF: ENABLE_NETWORK
          REPOS_FILE: .github/ros_sources.repos

  noble-jazzy-amd64:
    runs-on: ubuntu-24.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: noble
          DEB_ARCH: amd64
          ROS_DISTRO: jazzy
          SBUILD_CONF: $enable_network = 1;
          REPOS_FILE: .github/ros_sources.repos
